[package]
name = "drv8873"
version = "0.1.0"
edition = "2021"

[dependencies]
bitfield = "0.18.1"
embedded-hal = { version = "1.0.0", features = ["defmt-03"] }
embedded-hal-async = { version = "1.0.0", features = ["defmt-03"] }
num_enum = { version = "0.7.3", default-features = false }

[dev-dependencies]
embedded-hal-mock = { version = "0.11.1", features = ["embedded-hal-async"] }
async-std = { version = "1.13.0", features = ["attributes"] }
